### ISSUE TITLE
tomoStream python server crashes if tomoScan IOC is not running

### ISSUE THREAD

**Issue by decarlof** [xray-imaging/tomostream#43]
with error:
```
Traceback (most recent call last):
  File "start_tomostream.py", line 6, in <module>
    ts = TomoStream(["../../db/tomoStream_settings.req","../../db/tomoStream_settings.req"], {"$(P)":"2bmb:", "$(R)":"TomoStream:"})
  File "/local/tomo/conda/anaconda/envs/streaming/lib/python3.7/site-packages/tomostream-0.1-py3.7.egg/tomostream/tomostream.py", line 52, in __init__
    self.epics_pvs['ThetaArray']         = PV(self.epics_pvs['PSOPVPrefix'].get(as_string=True) + 'motorPos.AVAL')
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by decarlof** [comment]
adding [here](https://github.com/xray-imaging/tomostream/blob/e61097f7e64e2fdcfdce0b8691719ab69304f18f/tomostream/tomostream.py#L51):

```
if self.epics_pvs['PSOPVPrefix'].get(as_string=True) == None:
        log.error("TomoScan is down. Please start TomoScan first")
        exit() # this is ignored when starting this with pythion -i
        
```
does not work =  the error message is printed but the script keeps running in the interactive mode and I still get the error:

```
Traceback (most recent call last):
  File "start_tomostream.py", line 6, in <module>
    ts = TomoStream(["../../db/tomoStream_settings.req","../../db/tomoStream_settings.req"], {"$(P)":"2bmb:", "$(R)":"TomoStream:"})
  File "/local/tomo/conda/anaconda/envs/streaming/lib/python3.7/site-packages/tomostream-0.1-py3.7.egg/tomostream/tomostream.py", line 52, in __init__
    self.epics_pvs['ThetaArray']         = PV(self.epics_pvs['PSOPVPrefix'].get(as_string=True) + 'motorPos.AVAL')
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by decarlof** [comment]
@nikitinvv how about 
```
if self.epics_pvs['PSOPVPrefix'].get(as_string=True) == None:
        log.error("TomoScan is down")
        log.error("Type exit() here and start TomoScan first")
        return
        
```

this way 
```
python -i start_tomostream.py
2021-01-11 18:17:07,693 - TomoScan is down
2021-01-11 18:17:07,693 - Type exit() here and start TomoScan first
>>>
```

In other words I avoid the TypeError message, I print a red error log message, the python tomostream server is not set but its iterative session is still up and needs to be restarted
